spring.application.name=demo
spring.datasource.url=jdbc:postgresql://db:5432/demo
spring.datasource.username=demo
spring.datasource.password=demo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
